### ISSUE TITLE
Extra lines in Ages#.csv outputs

### ISSUE THREAD

**Issue by amforte** [jeanbraun/Pecube#12]
In the Ages#.csv outputs, the final entry on a given line actually appears on the next line. I've attached a screenshot from a text editor to illustrate what I mean. This was run on a mac. 
<img width="1259" alt="Screen Shot 2019-11-06 at 10 52 35 AM" src="https://user-images.githubusercontent.com/3410814/68319275-aeb47800-0083-11ea-92df-66d63cc5a72c.png">

**Comment by jeanbraun** [comment]
Thanks @amforte. I fixed this issue that was due to a missing descriptor in a format.
